version: '3.1'

services:
  backend:
    build:
      context: .
      dockerfile: ./compose/backend/DockerFile
    container_name: security-backend
    command: sh -c "./docker_script.sh"
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
